import assert from 'node:assert/strict'
import fs from 'node:fs'

const main = fs.readFileSync('src/main.tsx', 'utf8')
const adminApp = fs.readFileSync('src/quotes/AdminApp.tsx', 'utf8')
const authRouter = fs.readFileSync('src/quotes/AdminAuthRouter.tsx', 'utf8')
const experience = fs.readFileSync('src/quotes/AdminExperienceLayer.tsx', 'utf8')
const clientForm = fs.readFileSync('src/quotes/AdminClientForm.tsx', 'utf8')
const clients = fs.readFileSync('src/quotes/AdminClientsPage.tsx', 'utf8')
const clientsCss = fs.readFileSync('src/quotes/admin-clients-page.css', 'utf8')
const suspensions = fs.readFileSync('src/quotes/AdminSuspensionsPage.tsx', 'utf8')
const quotes = fs.readFileSync('src/quotes/AdminQuotes.tsx', 'utf8')
const shellCss = fs.readFileSync('src/quotes/admin-shell-navigation.css', 'utf8')
const passwordSecurity = fs.readFileSync('src/quotes/passwordSecurity.ts', 'utf8')
const cnpjFunction = fs.readFileSync('supabase/functions/cnpj-lookup/index.ts', 'utf8')

assert.match(main, /AdminAuthRouter/)
assert.doesNotMatch(main, /AdminExperienceLayer|AdminClientsPage|AdminSuspensionsPage/)
assert.match(authRouter, /<AdminMfaGate session=\{session\}><AdminApp \/><\/AdminMfaGate>/)
assert.match(adminApp, /AdminExperienceLayer/)
assert.match(adminApp, /AdminClientsPage/)
assert.match(adminApp, /AdminSuspensionsPage/)
assert.doesNotMatch(adminApp, /AdminOperationsHub|AdminPasswordControl|AdminDesktopNavigation/)
assert.match(experience, /Configurações/)
assert.match(experience, /Alterar senha/)
assert.match(experience, /secureUpdateAdminPassword\(password\)/)
assert.match(experience, /hrx-admin-shell-sidebar/)
assert.match(experience, /hrx-admin-shell-mobile-nav/)
assert.match(experience, /hrxSupabase\.auth\.signOut\(\)/)
assert.match(experience, /Encerrar sessão segura/)
assert.doesNotMatch(experience, /createPortal|MutationObserver|document\.querySelector/)
assert.match(shellCss, /hrx-admin-shell-sidebar/)
assert.match(shellCss, /hrx-admin-shell-mobile-nav/)
assert.match(passwordSecurity, /functions\.invoke\('admin-password'/)
assert.match(passwordSecurity, /mfa_required/)
assert.match(clientForm, /Consultar CNPJ/)
assert.match(clientForm, /cnpj-lookup/)
assert.match(clientForm, /Verificar cadastro na SEFAZ\/AM/)
assert.match(clients, /<AdminClientForm/)
assert.match(clients, /hrx_create_manual_quote/)
assert.match(clients, /mobileDetailOpen/)
assert.match(clients, /selectClient/)
assert.match(clients, /hrx-client-mobile-back/)
assert.match(clientsCss, /is-mobile-detail-open \.hrx-client-detail\{display:block\}/)
assert.match(clientsCss, /hrx-client-mobile-back/)
assert.match(suspensions, /hrx_suspend_quote/)
assert.match(suspensions, /hrx_resume_quote/)
assert.doesNotMatch(experience, /Consultar CNPJ|cnpj-lookup/)
assert.match(quotes, /Solicitações/)
for (const label of ['Visão executiva', 'Orçamentos', 'Clientes', 'Suspensões', 'Central de documentos', 'Painéis', 'Fiscal']) assert.match(experience, new RegExp(label))
assert.match(cnpjFunction, /validCnpj/)
assert.match(cnpjFunction, /admin_users/)
assert.match(cnpjFunction, /getClaims/)
assert.match(cnpjFunction, /aal2/)
assert.match(cnpjFunction, /brasilapi\.com\.br\/api\/cnpj\/v1/)

console.log('Admin experience checks passed')
