import assert from 'node:assert/strict'
import fs from 'node:fs'

const main = fs.readFileSync('src/main.tsx', 'utf8')
const experience = fs.readFileSync('src/quotes/AdminExperienceLayer.tsx', 'utf8')
const clientForm = fs.readFileSync('src/quotes/AdminClientForm.tsx', 'utf8')
const operations = fs.readFileSync('src/quotes/AdminOperationsHub.tsx', 'utf8')
const quotes = fs.readFileSync('src/quotes/AdminQuotes.tsx', 'utf8')
const css = fs.readFileSync('src/quotes/admin-experience.css', 'utf8')
const passwordSecurity = fs.readFileSync('src/quotes/passwordSecurity.ts', 'utf8')
const cnpjFunction = fs.readFileSync('supabase/functions/cnpj-lookup/index.ts', 'utf8')

assert.match(main, /AdminExperienceLayer/)
assert.doesNotMatch(main, /AdminPasswordControl/)
assert.match(experience, /Configurações/)
assert.match(experience, /Alterar senha/)
assert.match(experience, /secureUpdateAdminPassword\(password\)/)
assert.match(passwordSecurity, /functions\.invoke\('admin-password'/)
assert.match(passwordSecurity, /mfa_required/)
assert.match(clientForm, /Consultar CNPJ/)
assert.match(clientForm, /cnpj-lookup/)
assert.match(clientForm, /Verificar cadastro na SEFAZ\/AM/)
assert.match(operations, /AdminClientForm/)
assert.doesNotMatch(experience, /Consultar CNPJ/)
assert.doesNotMatch(experience, /cnpj-lookup/)
assert.match(quotes, /Solicitações/)
assert.match(experience, /Orçamentos/)
assert.match(experience, /Clientes/)
assert.match(experience, /Suspensões/)
assert.match(experience, /Central de documentos/)
assert.match(experience, /Painéis/)
assert.match(experience, /Fiscal/)
assert.match(css, /hrx-mobile-menu-launcher/)
assert.match(cnpjFunction, /validCnpj/)
assert.match(cnpjFunction, /admin_users/)
assert.match(cnpjFunction, /getClaims/)
assert.match(cnpjFunction, /aal2/)
assert.match(cnpjFunction, /brasilapi\.com\.br\/api\/cnpj\/v1/)

console.log('Admin experience checks passed')
