import assert from 'node:assert/strict'
import fs from 'node:fs'

const main = fs.readFileSync('src/main.tsx', 'utf8')
const adminApp = fs.readFileSync('src/quotes/AdminApp.tsx', 'utf8')
const unifiedRoot = fs.readFileSync('src/quotes/AdminUnifiedRoot.tsx', 'utf8')
const authRouter = fs.readFileSync('src/quotes/AdminAuthRouter.tsx', 'utf8')
const experience = fs.readFileSync('src/quotes/AdminExperienceLayer.tsx', 'utf8')
const liquidCss = fs.readFileSync('src/quotes/admin-liquid-glass.css', 'utf8')
const unifiedCss = fs.readFileSync('src/quotes/admin-unified-shell.css', 'utf8')
const clientForm = fs.readFileSync('src/quotes/AdminClientForm.tsx', 'utf8')
const suspensions = fs.readFileSync('src/quotes/AdminSuspensionsPage.tsx', 'utf8')
const quotes = fs.readFileSync('src/quotes/AdminQuotes.tsx', 'utf8')
const passwordSecurity = fs.readFileSync('src/quotes/passwordSecurity.ts', 'utf8')
const cnpjFunction = fs.readFileSync('supabase/functions/cnpj-lookup/index.ts', 'utf8')

assert.match(main, /AdminAuthRouter/)
assert.doesNotMatch(main, /AdminExperienceLayer|AdminClientsPage|AdminSuspensionsPage/)
assert.match(authRouter, /<AdminMfaGate session=\{session\}><AdminApp \/><\/AdminMfaGate>/)
assert.match(adminApp, /AdminUnifiedRoot/)
assert.doesNotMatch(adminApp, /<AdminExperienceLayer \/>|<AdminSuspensionsPage \/>|<AdminQuotes \/>/)
assert.match(unifiedRoot, /AdminExperienceLayer/)
assert.match(unifiedRoot, /AdminSuspensionsPage/)
assert.match(unifiedRoot, /AdminQuotes/)
assert.match(unifiedRoot, /data-admin-shell="desktop"/)
assert.match(unifiedRoot, /data-admin-shell="pwa"/)
assert.match(adminApp, /admin-liquid-glass\.css/)
assert.doesNotMatch(adminApp, /AdminOperationsHub|AdminPasswordControl|AdminDesktopNavigation/)

assert.match(experience, /Configurações/)
assert.match(experience, /Alterar senha/)
assert.match(experience, /secureUpdateAdminPassword\(password\)/)
assert.match(experience, /hrx-glass-sidebar/)
assert.match(experience, /hrx-mobile-nav/)
assert.match(experience, /hrxSupabase\.auth\.signOut\(\)/)
assert.match(experience, /hrx_create_manual_quote/)
assert.match(experience, /createSignedUrl/)
assert.match(experience, /storage\.from\('hrx-documents'\)\.upload/)
assert.doesNotMatch(experience, /createPortal|MutationObserver|document\.querySelector/)
assert.match(liquidCss, /hrx-glass-sidebar/)
assert.match(liquidCss, /hrx-mobile-nav/)
assert.match(liquidCss, /backdrop-filter/)
assert.match(liquidCss, /prefers-reduced-motion/)
assert.match(unifiedCss, /Neutralização dos shells internos antigos/)
assert.match(unifiedCss, /quote-commercial-shell>\.admin-exec-sidebar/)

assert.match(passwordSecurity, /functions\.invoke\('admin-password'/)
assert.match(passwordSecurity, /mfa_required/)
assert.match(clientForm, /Consultar CNPJ/)
assert.match(clientForm, /cnpj-lookup/)
assert.match(clientForm, /Verificar cadastro na SEFAZ\/AM/)
assert.match(suspensions, /hrx_suspend_quote/)
assert.match(suspensions, /hrx_resume_quote/)
assert.match(quotes, /Propostas/)
for (const label of ['Visão Geral', 'Projetos', 'Atividades', 'Clientes', 'Central de Documentos', 'Configurações']) assert.match(experience, new RegExp(label))
for (const label of ['Orçamentos', 'Suspensões', 'Fiscal']) assert.match(unifiedRoot, new RegExp(label))
assert.match(cnpjFunction, /validCnpj/)
assert.match(cnpjFunction, /admin_users/)
assert.match(cnpjFunction, /getClaims/)
assert.match(cnpjFunction, /aal2/)
assert.match(cnpjFunction, /brasilapi\.com\.br\/api\/cnpj\/v1/)

console.log('Admin unified Liquid Glass experience checks passed')
