import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('cálculo comercial usa centavos, imposto e ajuste de valor final', async () => {
  const [math, editor] = await Promise.all([read('src/quotes/quoteMath.ts'), read('src/quotes/AdminQuotes.tsx')])
  assert.match(math, /preDiscountCents/)
  assert.match(math, /taxCents/)
  assert.match(math, /customAdjustmentAmount/)
  assert.match(math, /buildInstallmentSchedule/)
  assert.match(editor, /RESUMO FINANCEIRO/)
  assert.match(editor, /Imposto estimado/)
  assert.match(editor, /Definir valor final/)
  assert.match(editor, /getAuthenticatorAssuranceLevel/)
})

test('salvamento unifica itens, cálculos, parcelas e histórico no backend', async () => {
  const [editor, backend] = await Promise.all([read('src/quotes/AdminQuotes.tsx'), read('supabase/functions/quote-admin/index.ts')])
  assert.match(editor, /action: 'save_quote'/)
  assert.match(backend, /action: 'save_quote'/)
  assert.match(backend, /resolveItems/)
  assert.match(backend, /quote_payment_installments/)
  assert.match(backend, /draft_saved/)
  assert.match(backend, /custom_final_amount_confirmed/)
})

test('gerador segue a Proposta Comercial Opção 3 Revisada em seis páginas fixas', async () => {
  const [editor, pdf, backend] = await Promise.all([read('src/quotes/AdminQuotes.tsx'), read('src/quotes/proposalPdf.ts'), read('supabase/functions/quote-admin/index.ts')])
  assert.match(pdf, /Proposta Comercial — Opção 3 Revisada/)
  assert.match(pdf, /Design ID: DAHTJI6gD7s/)
  assert.match(pdf, /const W = 794/)
  assert.match(pdf, /const H = 1123/)
  assert.match(pdf, /Documento comercial oficial/)
  assert.match(pdf, /01 — Apresentação/)
  assert.match(pdf, /02 — Objeto e escopo/)
  assert.match(pdf, /03 — Investimento/)
  assert.match(pdf, /04 — Condições comerciais/)
  assert.match(pdf, /05 — Aceite/)
  assert.match(pdf, /Uma proposta feita para ser clara, executiva e rastreável/)
  assert.match(pdf, /Soluções profissionais, escopo claro e condições comerciais transparentes/)
  for (const page of ['drawCover(', 'drawPresentation(', 'drawScope(', 'drawInvestment(', 'drawConditions(', 'drawAcceptance(']) assert.match(pdf, new RegExp(page.replace('(', '\\(')))
  assert.doesNotMatch(pdf, /itemChunks/)
  assert.match(editor, /navigator\.share/)
  assert.match(editor, /wa\.me/)
  assert.match(editor, /mailto:/)
  assert.match(editor, /navigator\.clipboard\.writeText/)
  assert.match(editor, /createSignedUrl/)
  assert.match(backend, /quote_versions/)
  assert.match(backend, /hrx_documents/)
  assert.match(backend, /Propostas Comerciais/)
})

test('mobile separa lista e editor e usa fluxo comercial por etapas', async () => {
  const [editor, css, chrome] = await Promise.all([read('src/quotes/AdminQuotes.tsx'), read('src/quotes/quote-commercial.css'), read('src/quotes/admin-unified-chrome.css')])
  assert.match(editor, /is-mobile-detail-open/)
  assert.match(editor, /quote-back/)
  assert.match(editor, /className="quote-steps"/)
  for (const label of ['Cliente', 'Itens', 'Valores', 'Pagamento', 'Revisão', 'Envio']) assert.match(editor, new RegExp(label))
  assert.match(css, /is-mobile-detail-open \.quote-queue/)
  assert.match(css, /is-mobile-detail-open \.quote-detail/)
  assert.match(css, /env\(safe-area-inset-bottom\)/)
  assert.match(chrome, /\.quote-stage\{order:1!important/)
  assert.match(chrome, /\.quote-summary\{order:2!important/)
  assert.match(chrome, /\.quote-steps\{[\s\S]*display:flex!important/)
})

test('ações de finalizar e excluir orçamento permanecem acessíveis acima do menu flutuante', async () => {
  const [brandFix, editor, index] = await Promise.all([read('public/hrx-brand-fix.css'), read('src/quotes/AdminQuotes.tsx'), read('index.html')])
  assert.match(brandFix, /quote-review-card > footer/)
  assert.match(brandFix, /position: sticky !important/)
  assert.match(brandFix, /bottom: calc\(82px \+ env\(safe-area-inset-bottom\)\)/)
  assert.match(brandFix, /quote-review-card > footer \.quote-primary/)
  assert.match(brandFix, /min-height: 50px/)
  assert.match(brandFix, /Excluir orçamento/)
  assert.match(editor, /confirmDelete/)
  assert.match(editor, /action: 'delete_draft'/)
  assert.match(editor, /commercial_status === 'draft'/)
  assert.match(editor, /current_version === 0/)
  assert.match(index, /hrx-brand-fix\.css\?v=6/)
})