-- Financeiro HRX - Tópico 2: estorno imutável de baixas e trilha de auditoria.
-- O registro original da baixa permanece preservado; o estorno apenas o marca como revertido.

alter table public.financial_settlements
  add column if not exists reversed_at timestamptz,
  add column if not exists reversed_by uuid references auth.users(id) on delete set null,
  add column if not exists reversal_reason text;

alter table public.financial_settlements drop constraint if exists financial_settlements_reversal_reason_check;
alter table public.financial_settlements add constraint financial_settlements_reversal_reason_check
  check (
    (reversed_at is null and reversal_reason is null)
    or
    (reversed_at is not null and char_length(trim(coalesce(reversal_reason, ''))) between 5 and 500)
  );

create index if not exists financial_settlements_active_entry_date_idx
  on public.financial_settlements(entry_id, settled_at desc, created_at desc)
  where reversed_at is null;

create table if not exists public.financial_audit_log (
  id bigint generated by default as identity primary key,
  entry_id uuid references public.financial_entries(id) on delete set null,
  settlement_id uuid references public.financial_settlements(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint financial_audit_event_type_length check (char_length(trim(event_type)) between 3 and 120)
);

create index if not exists financial_audit_entry_date_idx
  on public.financial_audit_log(entry_id, created_at desc);
create index if not exists financial_audit_settlement_date_idx
  on public.financial_audit_log(settlement_id, created_at desc);
create index if not exists financial_audit_event_date_idx
  on public.financial_audit_log(event_type, created_at desc);

create or replace function public.hrx_refresh_financial_entry_from_settlements()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid := coalesce(new.entry_id, old.entry_id);
  settled numeric(14,2);
  gross numeric(14,2);
  due date;
begin
  select coalesce(sum(amount), 0) into settled
  from public.financial_settlements
  where entry_id = target_id
    and reversed_at is null;

  select gross_amount, due_date into gross, due
  from public.financial_entries
  where id = target_id;

  if settled > gross then
    raise exception 'settlement_exceeds_entry_balance';
  end if;

  update public.financial_entries
  set paid_amount = settled,
      status = case
        when settled >= gross and gross > 0 then 'paid'
        when due < current_date then 'overdue'
        when settled > 0 then 'partial'
        else 'open'
      end,
      paid_at = case when settled >= gross and gross > 0 then now() else null end,
      updated_at = now()
  where id = target_id;

  return coalesce(new, old);
end;
$$;

alter table public.financial_audit_log enable row level security;

drop policy if exists financial_audit_log_admin on public.financial_audit_log;
create policy financial_audit_log_admin on public.financial_audit_log
  for select to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

drop policy if exists financial_audit_log_aal2 on public.financial_audit_log;
create policy financial_audit_log_aal2 on public.financial_audit_log
  as restrictive for select to authenticated
  using ((select auth.jwt()->>'aal') = 'aal2');

grant select on public.financial_audit_log to authenticated;
revoke insert, update, delete on public.financial_audit_log from authenticated;

revoke all on function public.hrx_refresh_financial_entry_from_settlements() from public, anon, authenticated;
grant execute on function public.hrx_refresh_financial_entry_from_settlements() to service_role;

comment on column public.financial_settlements.reversed_at is 'Momento em que a baixa foi estornada. O registro original permanece imutável para auditoria.';
comment on column public.financial_settlements.reversed_by is 'Administrador AAL2 responsável pelo estorno da baixa.';
comment on column public.financial_settlements.reversal_reason is 'Motivo obrigatório do estorno, preservado junto à baixa original.';
comment on table public.financial_audit_log is 'Trilha append-only das ações relevantes do Financeiro HRX.';
